### PR TITLE
Fixes #6 - Always cast integers to doubles for the in expression

### LINKED ISSUE #6: How to use `in` array operator with data?
I'm trying to use `in`operator with arrays. It works with inline data but I'm not able to make it work with data object.

```
assertEquals(true, jsonLogic.apply("""{"in": [1, [1, 2, 3]]}""", null)) // this works

val data1 = mapOf("value" to 1)
assertEquals(true, jsonLogic.apply("""{"in": [{"var": "value"}, [1, 2, 3]]}""", data1)) // does not work
val data2 = mapOf("list" to listOf(1, 2, 3))
assertEquals(true, jsonLogic.apply("""{"in": [1, {"var": "list"}]}""", data2)) // does not work
```

Am I doing something wrong? Or is it a bug?

### PR DESCRIPTION
**Pull request by jamsesso**

### CODE REVIEW

**Comment by pn** [comment]
Thanks for update! It looks better, but there is still one issue. This test from issue #6 does not pass (and I think it should):
```kotlin
val data = mapOf("value" to 1)
assertEquals(true, jsonLogic.apply("""{"in": [{"var": "value"}, [1, 2, 3]]}""", data))
```

Here are tests which I used:
```kotlin
    @Test
    fun test1() {
        assertEquals(true, jsonLogic.apply("""{"in": [1, [1, 2, 3]]}""", null))
        assertEquals(false, jsonLogic.apply("""{"in": [5, [1, 2, 3]]}""", null))
    }

    @Test
    fun test2() {
        assertEquals(true, jsonLogic.apply("""{"in": [1.0, [1.0, 2.0, 3.0]]}""", null))
        assertEquals(false, jsonLogic.apply("""{"in": [5.0, [1.0, 2.0, 3.0]]}""", null))
    }

    @Test
    fun test3() {
        val data1 = mapOf("value" to 1)
        assertEquals(true, jsonLogic.apply("""{"in": [{"var": "value"}, [1, 2, 3]]}""", data1)) // FIXME does not work
        assertEquals(false, jsonLogic.apply("""{"in": [{"var": "value"}, [2, 3, 4]]}""", data1))
    }

    @Test
    fun test4() {
        val data2 = mapOf("list" to listOf(1, 2, 3))
        assertEquals(true, jsonLogic.apply("""{"in": [1, {"var": "list"}]}""", data2)) // fixed in PR
        assertEquals(false, jsonLogic.apply("""{"in": [5, {"var": "list"}]}""", data2))
    }

    @Test
    fun test5() {
        assertEquals(true, jsonLogic.apply("""{"in": [1, [1.2, 1, 2, 3, 4.56]]}""", null))
        assertEquals(false, jsonLogic.apply("""{"in": [5, [1.2, 1, 2, 3, 4.56]]}""", null))
        assertEquals(true, jsonLogic.apply("""{"in": [4.56, [1, 2, 3, 4.56]]}""", null))
        assertEquals(false, jsonLogic.apply("""{"in": [4.57, [1, 2, 3, 4.56]]}""", null))
    }

    @Test
    fun test6() {
        val data1 = mapOf("list" to listOf(1.2, 1, 2, 3, 4.56))
        assertEquals(true, jsonLogic.apply("""{"in": [1, {"var": "list"}]}""", data1)) // fixed in PR
        assertEquals(false, jsonLogic.apply("""{"in": [5, {"var": "list"}]}""", data1))
        val data2 = mapOf("num" to 4.56)
        assertEquals(true, jsonLogic.apply("""{"in": [{"var": "num"}, [1, 2, 3, 4.56]]}""", data2))
        val data3 = mapOf("num" to 4.57)
        assertEquals(false, jsonLogic.apply("""{"in": [{"var": "num"}, [1, 2, 3, 4.56]]}""", data3))
    }
```

**Comment by jamsesso** [comment]
Ah yes it should pass. The problem is that Gson doesn't distinguish between integers and floating point (because of JS doesn't), so we need to bring everything into the evaluator as a double. I'll add that fix to the PR soon.

**Comment by jamsesso** [comment]
@pn Can you give this latest commit a try

**Comment by pn** [comment]
Looks ok to me :+1:

**Pull request merged**
